chore: remove healthcheck in dockerfile to fix build fail

diff --git a/apps/app/Dockerfile b/apps/app/Dockerfile
--- a/apps/app/Dockerfile
+++ b/apps/app/Dockerfile
@@ -9,7 +9,7 @@ FROM node:22-alpine AS builder
 
 RUN npm install -g bun@1.3.9
 
-RUN apk add --no-cache wget
+# RUN apk add --no-cache wget
 
 ARG NEXT_PUBLIC_DOMAIN
 ARG NEXT_PUBLIC_URL
@@ -97,9 +97,9 @@ USER app
 # Expose the API port (defaults to 3000 via .env, can be overridden)
 EXPOSE 3000
 
-HEALTHCHECK --interval=30s --timeout=5s --start-period=60s --retries=3 \
-  CMD \
-    wget -qO- http://localhost:3000/ > /dev/null || exit 1
+# HEALTHCHECK --interval=30s --timeout=5s --start-period=60s --retries=3 \
+#   CMD \
+#     wget -qO- http://localhost:3000/ > /dev/null || exit 1
 
 # Start the app
 CMD ["bun", "run", "--bun", "next", "start"] 
diff --git a/apps/website/Dockerfile b/apps/website/Dockerfile
--- a/apps/website/Dockerfile
+++ b/apps/website/Dockerfile
@@ -7,7 +7,7 @@
 # https://github.com/oven-sh/bun/issues/4795
 FROM node:22-alpine AS builder
 
-RUN apk add --no-cache wget
+# RUN apk add --no-cache wget
 
 RUN npm install -g bun@1.3.9
 
@@ -97,10 +97,10 @@ USER app
 EXPOSE 3000
 
 
-HEALTHCHECK --interval=30s --timeout=5s --start-period=60s --retries=3 \
-  CMD \
-    wget -qO- http://localhost:3000/ > /dev/null || exit 1 && \
-    wget -qO- http://localhost:3000/doc/environment/nextjs > /dev/null || exit 1
+# HEALTHCHECK --interval=30s --timeout=5s --start-period=60s --retries=3 \
+#   CMD \
+#     wget -qO- http://localhost:3000/ > /dev/null || exit 1 && \
+#     wget -qO- http://localhost:3000/doc/environment/nextjs > /dev/null || exit 1
 
 # Start the website
 CMD ["bun", "run", "--bun", "next", "start"] 
diff --git a/packages/@intlayer/design-system/Dockerfile b/packages/@intlayer/design-system/Dockerfile
--- a/packages/@intlayer/design-system/Dockerfile
+++ b/packages/@intlayer/design-system/Dockerfile
@@ -7,7 +7,7 @@ FROM node:22-alpine AS builder
 
 RUN npm install -g bun@1.3.9
 
-RUN apk add --no-cache nodejs npm wget
+# RUN apk add --no-cache nodejs npm wget
 
 # Put the repo in /workspace
 WORKDIR /workspace
@@ -59,9 +59,9 @@ WORKDIR /workspace/packages/@intlayer/design-system
 # Build the intlayer dictionaries (optional if turbo already did what you need)
 RUN bun x intlayer build
 
-HEALTHCHECK --interval=30s --timeout=5s --start-period=60s --retries=3 \
-  CMD \
-    wget -qO- http://localhost:6006/ > /dev/null || exit 1
+# HEALTHCHECK --interval=30s --timeout=5s --start-period=60s --retries=3 \
+#   CMD \
+#     wget -qO- http://localhost:6006/ > /dev/null || exit 1
 
 
 
@@ -85,9 +85,9 @@ COPY --from=builder /workspace/packages/@intlayer/design-system/storybook-static
 
 EXPOSE 6006
 
-HEALTHCHECK --interval=30s --timeout=5s --start-period=60s --retries=3 \
-  CMD \
-    wget -qO- http://localhost:6006/ > /dev/null || exit 1
+# HEALTHCHECK --interval=30s --timeout=5s --start-period=60s --retries=3 \
+#   CMD \
+#     wget -qO- http://localhost:6006/ > /dev/null || exit 1
 
 # -f foreground, -p port, -h doc root
 CMD ["bun", "x", "serve", ".", "-l", "6006"]
